// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmTcAXFawzLxnWDq5SLO7E4qCGGEeYU8',
    appId: '1:1063344238231:web:09f329fd4a62b4d8f283d2',
    messagingSenderId: '1063344238231',
    projectId: 'loadmatch-order-app',
    authDomain: 'loadmatch-order-app.firebaseapp.com',
    storageBucket: 'loadmatch-order-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Ozr2GI8xGhZeCzVeCXwd2Z_VtnnUcIQ',
    appId: '1:1063344238231:android:cb1cdeca29711cc8f283d2',
    messagingSenderId: '1063344238231',
    projectId: 'loadmatch-order-app',
    storageBucket: 'loadmatch-order-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsp6EzZOr4N2MbZDd2IlqI3fwt15teVQ',
    appId: '1:1063344238231:ios:0ea6208263ab8c72f283d2',
    messagingSenderId: '1063344238231',
    projectId: 'loadmatch-order-app',
    storageBucket: 'loadmatch-order-app.appspot.com',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxsp6EzZOr4N2MbZDd2IlqI3fwt15teVQ',
    appId: '1:1063344238231:ios:54394728f8c1f35cf283d2',
    messagingSenderId: '1063344238231',
    projectId: 'loadmatch-order-app',
    storageBucket: 'loadmatch-order-app.appspot.com',
    iosBundleId: 'com.example.orderApp.RunnerTests',
  );
}
